networks:
  my-network:
    driver: bridge

services:
  web:
    build: ./src
    hostname: sample_go_app_host
    ports:
      - "8000:8000"
    networks:
      - my-network
    environment:
      NEW_RELIC_LICENSE_KEY: ${NR_LICENSE_KEY?err}
      NEW_RELIC_APP_NAME: ${NR_APP_NAME?err}
      NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"

  load:
    build: ./test
    networks:
      - my-network
