name: Run App for Lab

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NR_LICENSE_KEY: ${{ secrets.NR_LICENSE_KEY }}
      NR_APP_NAME: "sample_go_app"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Update packages
        run: |
          sudo apt-get update

      - name: Remove conflicts and Install Docker
        run: |
          sudo apt-get remove moby-containerd moby-runc
          sudo apt-get install -y docker.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run Docker Compose with a 60m timer
        run: |
          docker-compose -f compose.yml up -d
          sleep 3h # Leave these containers running for 3 hours (max: 6)
      
      - name: Stop containers
        run: |
          docker-compose -f compose.yml down || true
